#' Scale stream or precipitation chemical flux by watershed area
#'
#' MacroSheds chemical flux is scaled to watershed area by default (kg/ha/d).
#' This function converts chemical flux to kg/d. If You generated precipitation chemical
#' flux yourself with [ms_calc_watershed_precip()], it is in kg/d and this function may be needed.
#'
#' @author Spencer Rhea, \email{spencerrhea41@@gmail.com}
#' @author Mike Vlah
#' @author Wes Slaughter
#' @param d \code{data.frame}. A \code{data.frame} in MacroSheds format (see [MacroSheds dataset](https://doi.org/10.6084/m9.figshare.c.5621740) for definitions),
#'    containing stream or precipitation flux data. A \code{data.frame} in
#'    MacroSheds format is generated by [ms_load_product()]. 
#' @param site_data \code{data.frame}. Optional; if supplied, should be the MacroSheds
#'    site_data tibble as returned by [ms_download_site_data()]. If omitted,
#'    [ms_download_site_data()] will be called for you.
#' @return returns a \code{data.frame} in MacroSheds format with stream or precipitation chemical flux in kg/ha/d.
#' @details MacroSheds reports all chemical flux on a per area basis (kg/ha/d) to
#'    facilitate comparison of watersheds of different sizes. If you've unscaled 
#'    MacroSheds flux data with [ms_undo_scale_flux_by_area()], or generated
#'    precipitation flux with [ms_calc_watershed_precip()], you can use this function
#'    to convert from kg/d to kd/ha/d. To download MacroSheds data, see [ms_download_core_data()].
#' @export
#' @seealso [ms_undo_scale_flux_by_area()]
#' @examples
#' ### Load some MacroSheds data:
#' ms_root = 'data/macrosheds'
#' ms_download_core_data(macrosheds_root = ms_root,
#'                       domains = 'hbef')
#' d <- ms_load_product(macrosheds_root = ms_root, 
#'                      prodname = 'stream_flux_inst_scaled', 
#'                      domains = 'hbef',
#'                      filter_vars = 'NO3_N')
#'
#' d <- ms_undo_scale_flux_by_area(d)
#' d <- ms_scale_flux_by_area(d)

ms_scale_flux_by_area <- function(d, site_data){
    
    if(missing(site_data)){
        site_data <- ms_download_site_data()
    } else{
        if(! 'ws_area_ha' %in% colnames(site_data)){
            stop('site_data has been modified from default. omit this argument to retrieve site_data automatically.')
        }
    }
    
    sites <- unique(d$site_code)
    
    ws_areas <- site_data %>%
        select(site_code, ws_area_ha) %>%
        filter(site_code %in% !!sites)
    
    d <- d %>%
        left_join(ws_areas,
                  by = 'site_code') %>%
        mutate(val = val / ws_area_ha) %>%
        select(-ws_area_ha)

    return(d)
}