#' Un-scale stream or precipitation chemical flux by watershed area
#'
#' MacroSheds chemical flux is scaled to watershed area by default (kg/ha/d).
#' This function converts chemical flux to kg/d. If You generated precipitation chemical
#' flux yourself with [ms_calc_watershed_precip()], it is in kd/d and this function is not needed.
#'
#' @author Spencer Rhea, \email{spencerrhea41@@gmail.com}
#' @author Mike Vlah
#' @author Wes Slaughter
#' @param d \code{data.frame}. A \code{data.frame} in MacroSheds format (see [MacroSheds documentation](EDI link pending) for definitions),
#'    containing stream_flux_inst_scaled or precip_flux_inst_scaled data. A \code{data.frame} in
#'    MacroSheds format is generated by [ms_load_product()]. 
#' @return returns a \code{data.frame} in MacroSheds format with stream or precipitation chemical flux in kg/d.
#' @details MacroSheds reports all chemical flux on a per area basis (kg/ha/d) to
#'    facilitate comparison of watersheds of different sizes. Sometimes un-scaled 
#'    fluxes are of interest. This function will convert the units of a native 
#'    MacroSheds chemical flux dataset from kg/ha/d to kg/d. To download
#'    MacroSheds data, see [ms_download_core_data()].
#' @export
#' @seealso [ms_scale_flux_by_area()]
#' @examples
#' ### Load some MacroSheds data:
#' ms_root = 'data/macrosheds'
#' ms_download_core_data(macrosheds_root = ms_root,
#'                       domains = 'hbef')
#' d <- ms_load_product(macrosheds_root = ms_root, 
#'                      prodname = 'stream_flux_inst_scaled', 
#'                      domains = 'hbef',
#'                      filter_vars = 'NO3_N')
#'
#' d <- ms_undo_scale_flux_by_area(d)

ms_undo_scale_flux_by_area <- function(d){

    library("dplyr", quietly = TRUE)
    
    requireNamespace('macrosheds', quietly = TRUE)

    site_data <- macrosheds::ms_site_data
    
    sites <- unique(d$site_code)
    
    ws_areas <- site_data %>%
        dplyr::select(site_code, ws_area_ha) %>%
        filter(site_code %in% !!sites)
    
    d <- d %>%
        left_join(ws_areas,
                  by = 'site_code') %>%
        mutate(val = val * ws_area_ha) %>%
        dplyr::select(-ws_area_ha)

    return(d)
}
