#' Un-scale stream chemical flux by watershed area
#'
#' MacroSheds stream chemical flux is scaled to watershed area by default (kg/ha/d).
#' This function converts stream chemical flux to kg/d.
#'
#' @author Spencer Rhea, \email{spencerrhea41@gmail.com}
#' @author Mike Vlah
#' @author Wes Slaughter
#' @param d \code{date.frame}. A \code{data.frame} in MacroSheds format (see PLACEHOLDER0 for definitions),
#'    containing stream_flux_inst_scaled or precip_flux_inst_scaled data. A \code{data.frame} in
#'    MacroSheds format is generated by [ms_load_product()]. 
#' @param site_data \code{data.frame}. Optional; if supplied, should be the MacroSheds
#'    site_data tibble as returned by [ms_download_site_data()]. If omitted,
#'    [ms_download_site_data()] will be called for you.
#' @return returns a \code{data.frame} in MacroSheds format with stream chemical flux in kg/d.
#' @details MacroSheds reports all chemical flux on a per area basis (kg/ha/d) to
#'    facilitate comparison of watersheds of different sizes. Sometimes un-scaled 
#'    fluxes are of interest. This function will convert the units of a native 
#'    MacroSheds stream chemical flux dataset from kg/ha/d to kg/d. To download
#'    MacroSheds data, see [ms_download_core_data()].
#' @export
#' @examples
#' ### Load some MacroSheds data:
#' ms_root = 'data/macrosheds'
#' ms_download_core_data(macrosheds_root = ms_root,
#'                       domains = 'hbef')#'                      
#' d <- ms_load_product(macrosheds_root = ms_root, 
#'                      prodname = 'stream_flux_inst_scaled', 
#'                      domains = 'hbef',
#'                      filter_vars = 'NO3_N')
#'
#' d <- ms_undo_scale_flux_by_area(d)

ms_undo_scale_flux_by_area <- function(d, site_data){
    
    if(missing(site_data)){
        site_data <- ms_download_site_data()
    } else{
        if(! 'ws_area_ha' %in% colnames(site_data)){
            stop('site_data has been modified from default. omit this argument to retrieve site_data automatically.')
        }
    }
    
    sites <- unique(d$site_code)
    
    ws_areas <- site_data %>%
        select(site_code, ws_area_ha) %>%
        filter(site_code %in% !!sites)
    
    d <- d %>%
        left_join(ws_areas,
                  by = 'site_code') %>%
        mutate(val = sw(val * ws_area_ha)) %>%
        select(-ws_area_ha)

    return(d)
}